export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { apiHandler } from "@/lib/middleware/api-handler";
import { withAuth } from "@/lib/middleware/with-auth";
import { queryAll, run } from '@/lib/db';

function getNextDate(currentDate: string, frequency: string): string {
    const date = new Date(currentDate);
    if (frequency === 'weekly') {
        date.setDate(date.getDate() + 7);
    } else if (frequency === 'monthly') {
        date.setMonth(date.getMonth() + 1);
    } else if (frequency === 'yearly') {
        date.setFullYear(date.getFullYear() + 1);
    }
    return date.toISOString().split('T')[0];
}

export const POST = apiHandler(
    withAuth(async (request: NextRequest, { userId }) => {
        const today = new Date().toISOString().split('T')[0];
        let syncedCount = 0;

        // 1. Process Recurring Transactions
        const recurring = await queryAll<any>(
            'SELECT * FROM recurring_transactions WHERE user_id = ? AND active = 1 AND next_date <= ?',
            [userId, today]
        );

        for (const item of recurring) {
            let currentDate = item.next_date;
            
            // Loop in case they haven't logged in for multiple cycles
            while (currentDate <= today) {
                await run(
                    'INSERT INTO transactions (user_id, type, amount, category, description, date, notes) VALUES (?, ?, ?, ?, ?, ?, ?)',
                    [userId, item.type, item.amount, item.category, `${item.name} (Auto-recurring)`, currentDate, 'Auto-generated by recurring schedule']
                );
                
                await run(
                    'INSERT INTO notifications (user_id, type, title, message) VALUES (?, ?, ?, ?)',
                    [userId, 'info', 'Recurring Transaction Added', `${item.name} (${item.amount}) was added for ${currentDate}.`]
                );

                // If tied to a household space, auto-create household expense and split fan-out
                if (item.household_id && item.type === 'expense') {
                    try {
                        const expResult = await run(
                            'INSERT INTO household_expenses (household_id, user_id, description, amount, category, split_between) VALUES (?, ?, ?, ?, ?, ?)',
                            [item.household_id, userId, `[Auto Recurring] ${item.name}`, item.amount, item.category, 'all']
                        );
                        const hhMembers = await queryAll<{ user_id: number }>(
                            'SELECT user_id FROM household_members WHERE household_id = ?',
                            [item.household_id]
                        );
                        if (hhMembers.length > 1) {
                            const splitAmount = Math.round((item.amount / hhMembers.length) * 100) / 100;
                            for (const member of hhMembers) {
                                if (member.user_id !== userId) {
                                    await run(
                                        'INSERT INTO household_settlements (household_id, payer_id, payee_id, amount, status) VALUES (?, ?, ?, ?, ?)',
                                        [item.household_id, member.user_id, userId, splitAmount, 'pending']
                                    );
                                }
                            }
                        }
                    } catch (hhErr) {
                        console.error('[sync] Household auto-split failed for recurring transaction:', hhErr);
                    }
                }

                currentDate = getNextDate(currentDate, item.frequency);
                syncedCount++;
            }

            // Update the next_date
            await run(
                'UPDATE recurring_transactions SET next_date = ? WHERE id = ?',
                [currentDate, item.id]
            );
        }

        // 2. Process Subscriptions
        const subscriptions = await queryAll<any>(
            'SELECT * FROM subscriptions WHERE user_id = ? AND is_active = 1 AND next_renewal_date <= ?',
            [userId, today]
        );

        for (const sub of subscriptions) {
            let currentDate = sub.next_renewal_date;

            while (currentDate <= today) {
                await run(
                    'INSERT INTO transactions (user_id, type, amount, category, description, date, notes) VALUES (?, ?, ?, ?, ?, ?, ?)',
                    [userId, 'expense', sub.amount, sub.category, `${sub.name} (Subscription)`, currentDate, 'Auto-generated subscription payment']
                );

                await run(
                    'INSERT INTO notifications (user_id, type, title, message) VALUES (?, ?, ?, ?)',
                    [userId, 'info', 'Subscription Renewed', `Your ${sub.name} subscription (${sub.amount}) was renewed.`]
                );

                currentDate = getNextDate(currentDate, sub.billing_cycle);
                syncedCount++;
            }

            await run(
                'UPDATE subscriptions SET next_renewal_date = ? WHERE id = ?',
                [currentDate, sub.id]
            );
        }

        return NextResponse.json({ success: true, syncedCount });
    })
);
