import { randomUUID } from 'crypto';
import { DataAction, ParsedFinancialData } from '@/lib/ai';
import { queryOne, run } from '@/lib/db';
import { maybeCreateBudgetAlert } from '@/lib/alerts';

export interface ActionResult {
    action: string;
    target: string;
    count: number;
    detail: string;
    requiresApproval?: boolean;
    status?: 'PENDING_APPROVAL' | 'EXECUTED' | 'REJECTED';
    actionLogId?: string;
    amount?: number;
}

export interface StoredTransaction {
    id: number;
    type: string;
    amount: number;
    category: string;
    description: string;
    date: string;
}

/** Configurable threshold above which create/edit requires confirmation */
export const HIGH_VALUE_THRESHOLD = Number(process.env.AGENT_ACTION_APPROVAL_THRESHOLD || 10000);

/**
 * Checks if an action is destructive (delete/reset) or high-value and therefore
 * requires user confirmation before execution.
 */
export function isActionApprovalRequired(action: DataAction): { required: boolean; reason: string; amount?: number } {
    if (action.type === 'reset') {
        return { required: true, reason: `Resetting data in ${action.target} will permanently delete records.` };
    }

    if (action.type === 'delete') {
        const filterDesc = action.filter?.category
            ? ` for category "${action.filter.category}"`
            : action.filter?.description
                ? ` matching "${action.filter.description}"`
                : action.filter?.id
                    ? ` with ID #${action.filter.id}`
                    : '';
        return { required: true, reason: `Delete ${action.target}${filterDesc}? This action cannot be undone.` };
    }

    // High value create / edit check
    const u = action.updates || {};
    const candidateAmount = u.amount ?? u.monthly_limit ?? u.balance ?? u.target_amount ?? u.current_balance ?? u.opening_balance ?? u.avg_cost_basis;

    if (candidateAmount !== undefined && candidateAmount !== null && candidateAmount >= HIGH_VALUE_THRESHOLD) {
        const name = u.name || u.description || u.category || action.target;
        return {
            required: true,
            reason: `Action involves high value of ${candidateAmount.toLocaleString()} (${action.type} ${name}). Confirm before proceeding?`,
            amount: candidateAmount,
        };
    }

    return { required: false, reason: '' };
}

/**
 * Executes or gates data actions generated by AI Coach.
 * Destructive/high-value actions are staged in agent_action_logs as PENDING_APPROVAL.
 */
export async function processDataActions(
    actions: DataAction[],
    userId: number,
    sessionId?: string,
    bypassApproval = false
): Promise<ActionResult[]> {
    const results: ActionResult[] = [];
    const currentMonth = new Date().getMonth() + 1;
    const currentYear = new Date().getFullYear();

    for (const action of actions) {
        try {
            // Safety approval check
            if (!bypassApproval) {
                const approvalCheck = isActionApprovalRequired(action);
                if (approvalCheck.required) {
                    const actionLogId = `act_${randomUUID()}`;
                    const actionType = `${action.type.toUpperCase()}_${action.target.toUpperCase()}`;

                    await run(
                        `INSERT INTO agent_action_logs (id, user_id, session_id, action_type, payload_json, status, created_at)
                         VALUES (?, ?, ?, ?, ?, 'PENDING_APPROVAL', unixepoch())`,
                        [actionLogId, userId, sessionId || null, actionType, JSON.stringify(action)]
                    );

                    try {
                        await run(
                            `INSERT INTO chat_tool_executions (user_id, tool_name, parameters_json, status)
                             VALUES (?, ?, ?, 'pending')`,
                            [userId, `${action.type}_${action.target}`, JSON.stringify({ actionLogId, action })]
                        );
                    } catch {
                        // table may not be initialized or have different schema; ignore
                    }

                    results.push({
                        action: action.type,
                        target: action.target,
                        count: 0,
                        detail: approvalCheck.reason,
                        requiresApproval: true,
                        status: 'PENDING_APPROVAL',
                        actionLogId,
                        amount: approvalCheck.amount,
                    });
                    continue;
                }
            }

            if (action.type === 'reset') {
                const targets = action.target === 'all'
                    ? [
                        'transactions',
                        'budgets',
                        'networth',
                        'notifications',
                        'chat_history',
                        'debts',
                        'recurring_transactions',
                        'investment_holdings',
                        'accounts',
                        'savings_goals'
                    ] as const
                    : [action.target] as const;

                let totalDeleted = 0;
                for (const target of targets) {
                    const tableMap: Record<string, string> = {
                        transactions: 'transactions',
                        budgets: 'budgets',
                        networth: 'net_worth',
                        notifications: 'notifications',
                        chat_history: 'chat_messages',
                        debts: 'debts',
                        recurring_transactions: 'recurring_transactions',
                        recurring: 'recurring_transactions',
                        investment_holdings: 'investment_holdings',
                        investments: 'investment_holdings',
                        accounts: 'accounts',
                        savings_goals: 'savings_goals',
                    };
                    const table = tableMap[target];
                    if (table) {
                        try {
                            const res = await run(`DELETE FROM ${table} WHERE user_id = ?`, [userId]);
                            totalDeleted += res.rowsAffected;
                        } catch {
                            // table may not exist
                        }
                    }
                }
                results.push({
                    action: 'reset',
                    target: action.target,
                    count: totalDeleted,
                    status: 'EXECUTED',
                    detail: action.target === 'all'
                        ? `Cleared all financial data (${totalDeleted} records removed)`
                        : `Cleared ${action.target} (${totalDeleted} records removed)`,
                });
            } else if (action.type === 'delete') {
                const count = await executeDelete(action, userId, currentMonth, currentYear);
                results.push({
                    action: 'delete',
                    target: action.target,
                    count,
                    status: 'EXECUTED',
                    detail: `Deleted ${count} ${action.target} record${count !== 1 ? 's' : ''}`,
                });
            } else if (action.type === 'edit') {
                const count = await executeEdit(action, userId, currentMonth, currentYear);
                results.push({
                    action: 'edit',
                    target: action.target,
                    count,
                    status: 'EXECUTED',
                    detail: `Updated ${count} ${action.target} record${count !== 1 ? 's' : ''}`,
                });
            } else if (action.type === 'create') {
                const count = await executeCreate(action, userId, currentMonth, currentYear);
                results.push({
                    action: 'create',
                    target: action.target,
                    count,
                    status: 'EXECUTED',
                    detail: `Created ${count} ${action.target} record${count !== 1 ? 's' : ''}`,
                });
            }
        } catch (error) {
            console.error('Action error:', action, error);
            results.push({
                action: action.type,
                target: action.target,
                count: 0,
                status: 'REJECTED',
                detail: `Failed to ${action.type} ${action.target}`,
            });
        }
    }

    return results;
}

/**
 * Executes or rejects an action that was previously pending user approval.
 */
export async function executeApprovedAgentAction(
    actionLogId: string,
    userId: number,
    approved: boolean
): Promise<{ success: boolean; status: string; detail: string; count?: number }> {
    const log = await queryOne<{
        id: string;
        user_id: number;
        action_type: string;
        payload_json: string;
        status: string;
    }>('SELECT * FROM agent_action_logs WHERE id = ? AND user_id = ?', [actionLogId, userId]);

    if (!log) {
        return { success: false, status: 'NOT_FOUND', detail: 'Action request not found' };
    }

    if (log.status !== 'PENDING_APPROVAL') {
        return { success: false, status: log.status, detail: `Action already processed (${log.status})` };
    }

    const nowEpoch = Math.floor(Date.now() / 1000);

    if (!approved) {
        await run('UPDATE agent_action_logs SET status = ?, executed_at = ? WHERE id = ?', [
            'REJECTED',
            nowEpoch,
            actionLogId,
        ]);

        try {
            await run("UPDATE chat_tool_executions SET status = 'cancelled' WHERE parameters_json LIKE ?", [
                `%${actionLogId}%`,
            ]);
        } catch { /* ignore */ }

        return { success: true, status: 'REJECTED', detail: 'Action cancelled by user' };
    }

    // Approved: execute action with bypassApproval = true
    const action: DataAction = JSON.parse(log.payload_json);
    const results = await processDataActions([action], userId, undefined, true);
    const res = results[0];

    await run('UPDATE agent_action_logs SET status = ?, executed_at = ? WHERE id = ?', [
        'EXECUTED',
        nowEpoch,
        actionLogId,
    ]);

    try {
        await run("UPDATE chat_tool_executions SET status = 'executed', executed_at = ? WHERE parameters_json LIKE ?", [
            new Date().toISOString(),
            `%${actionLogId}%`,
        ]);
    } catch { /* ignore */ }

    return {
        success: true,
        status: 'EXECUTED',
        detail: res?.detail || `Executed ${action.type} on ${action.target}`,
        count: res?.count ?? 0,
    };
}

async function executeDelete(action: DataAction, userId: number, currentMonth: number, currentYear: number): Promise<number> {
    const f = action.filter || {};

    if (action.target === 'transactions') {
        if (f.id) return (await run('DELETE FROM transactions WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        if (f.ids && f.ids.length > 0) {
            let total = 0;
            for (const id of f.ids) total += (await run('DELETE FROM transactions WHERE id = ? AND user_id = ?', [id, userId])).rowsAffected;
            return total;
        }

        const conditions = ['user_id = ?'];
        const params: unknown[] = [userId];
        if (f.category) { conditions.push('LOWER(category) = LOWER(?)'); params.push(f.category); }
        if (f.description) { conditions.push('LOWER(description) LIKE LOWER(?)'); params.push(`%${f.description}%`); }
        if (f.date) { conditions.push('date = ?'); params.push(f.date); }
        if (f.dateFrom) { conditions.push('date >= ?'); params.push(f.dateFrom); }
        if (f.dateTo) { conditions.push('date <= ?'); params.push(f.dateTo); }
        if (f.transactionType) { conditions.push('type = ?'); params.push(f.transactionType); }
        return (await run(`DELETE FROM transactions WHERE ${conditions.join(' AND ')}`, params)).rowsAffected;
    }

    if (action.target === 'budgets') {
        if (f.id) return (await run('DELETE FROM budgets WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        if (f.category) {
            return (await run(
                'DELETE FROM budgets WHERE user_id = ? AND LOWER(category) = LOWER(?) AND month = ? AND year = ?',
                [userId, f.category, currentMonth, currentYear]
            )).rowsAffected;
        }
        return (await run('DELETE FROM budgets WHERE user_id = ? AND month = ? AND year = ?', [userId, currentMonth, currentYear])).rowsAffected;
    }

    if (action.target === 'networth') {
        if (f.id) return (await run('DELETE FROM net_worth WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        return (await run('DELETE FROM net_worth WHERE user_id = ?', [userId])).rowsAffected;
    }

    if (action.target === 'notifications') {
        if (f.id) return (await run('DELETE FROM notifications WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        return (await run('DELETE FROM notifications WHERE user_id = ?', [userId])).rowsAffected;
    }

    if (action.target === 'chat_history') {
        return (await run('DELETE FROM chat_messages WHERE user_id = ?', [userId])).rowsAffected;
    }

    if (action.target === 'debts') {
        if (f.id) return (await run('DELETE FROM debts WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        if (f.ids && f.ids.length > 0) {
            let total = 0;
            for (const id of f.ids) total += (await run('DELETE FROM debts WHERE id = ? AND user_id = ?', [id, userId])).rowsAffected;
            return total;
        }
        if (f.name || f.description) {
            return (await run('DELETE FROM debts WHERE user_id = ? AND LOWER(name) LIKE LOWER(?)', [userId, `%${f.name || f.description}%`])).rowsAffected;
        }
        return (await run('DELETE FROM debts WHERE user_id = ?', [userId])).rowsAffected;
    }

    if (action.target === 'recurring_transactions' || action.target === 'recurring') {
        if (f.id) return (await run('DELETE FROM recurring_transactions WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        if (f.ids && f.ids.length > 0) {
            let total = 0;
            for (const id of f.ids) total += (await run('DELETE FROM recurring_transactions WHERE id = ? AND user_id = ?', [id, userId])).rowsAffected;
            return total;
        }
        if (f.name || f.description) {
            return (await run('DELETE FROM recurring_transactions WHERE user_id = ? AND LOWER(name) LIKE LOWER(?)', [userId, `%${f.name || f.description}%`])).rowsAffected;
        }
        return (await run('DELETE FROM recurring_transactions WHERE user_id = ?', [userId])).rowsAffected;
    }

    if (action.target === 'investment_holdings' || action.target === 'investments') {
        if (f.id) return (await run('DELETE FROM investment_holdings WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        if (f.ids && f.ids.length > 0) {
            let total = 0;
            for (const id of f.ids) total += (await run('DELETE FROM investment_holdings WHERE id = ? AND user_id = ?', [id, userId])).rowsAffected;
            return total;
        }
        if (f.ticker) {
            return (await run('DELETE FROM investment_holdings WHERE user_id = ? AND UPPER(ticker) = UPPER(?)', [userId, f.ticker])).rowsAffected;
        }
        if (f.name || f.description) {
            return (await run('DELETE FROM investment_holdings WHERE user_id = ? AND LOWER(name) LIKE LOWER(?)', [userId, `%${f.name || f.description}%`])).rowsAffected;
        }
        return (await run('DELETE FROM investment_holdings WHERE user_id = ?', [userId])).rowsAffected;
    }

    if (action.target === 'accounts') {
        if (f.id) return (await run('DELETE FROM accounts WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        if (f.ids && f.ids.length > 0) {
            let total = 0;
            for (const id of f.ids) total += (await run('DELETE FROM accounts WHERE id = ? AND user_id = ?', [id, userId])).rowsAffected;
            return total;
        }
        if (f.name || f.description) {
            return (await run('DELETE FROM accounts WHERE user_id = ? AND LOWER(name) LIKE LOWER(?)', [userId, `%${f.name || f.description}%`])).rowsAffected;
        }
        return (await run('DELETE FROM accounts WHERE user_id = ?', [userId])).rowsAffected;
    }

    if (action.target === 'savings_goals') {
        if (f.id) return (await run('DELETE FROM savings_goals WHERE id = ? AND user_id = ?', [f.id, userId])).rowsAffected;
        if (f.name || f.description) {
            return (await run('DELETE FROM savings_goals WHERE user_id = ? AND LOWER(name) LIKE LOWER(?)', [userId, `%${f.name || f.description}%`])).rowsAffected;
        }
        return (await run('DELETE FROM savings_goals WHERE user_id = ?', [userId])).rowsAffected;
    }

    return 0;
}

async function executeEdit(action: DataAction, userId: number, currentMonth: number, currentYear: number): Promise<number> {
    const f = action.filter || {};
    const u = action.updates || {};

    if (action.target === 'transactions') {
        const sets: string[] = [];
        const setParams: unknown[] = [];
        if (u.amount !== undefined && u.amount !== null) { sets.push('amount = ?'); setParams.push(u.amount); }
        if (u.category) { sets.push('category = ?'); setParams.push(u.category); }
        if (u.description) { sets.push('description = ?'); setParams.push(u.description); }
        if (u.date) { sets.push('date = ?'); setParams.push(u.date); }
        if (u.type) { sets.push('type = ?'); setParams.push(u.type); }
        if (sets.length === 0) return 0;

        const conditions = ['user_id = ?'];
        const whereParams: unknown[] = [userId];
        if (f.id) { conditions.push('id = ?'); whereParams.push(f.id); }
        else {
            if (f.category) { conditions.push('LOWER(category) = LOWER(?)'); whereParams.push(f.category); }
            if (f.description) { conditions.push('LOWER(description) LIKE LOWER(?)'); whereParams.push(`%${f.description}%`); }
            if (f.date) { conditions.push('date = ?'); whereParams.push(f.date); }
            if (f.dateFrom) { conditions.push('date >= ?'); whereParams.push(f.dateFrom); }
            if (f.dateTo) { conditions.push('date <= ?'); whereParams.push(f.dateTo); }
            if (f.transactionType) { conditions.push('type = ?'); whereParams.push(f.transactionType); }
        }

        const result = await run(`UPDATE transactions SET ${sets.join(', ')} WHERE ${conditions.join(' AND ')}`, [...setParams, ...whereParams]);
        if (result.rowsAffected > 0 && (u.type === 'expense' || (!u.type && action.target === 'transactions'))) {
            await maybeCreateBudgetAlert({
                userId,
                type: u.type || 'expense',
                category: u.category || f.category || '',
                date: u.date || f.date || new Date().toISOString().split('T')[0],
            });
        }
        return result.rowsAffected;
    }

    if (action.target === 'budgets') {
        const sets: string[] = [];
        const setParams: unknown[] = [];
        if (u.monthly_limit !== undefined && u.monthly_limit !== null) { sets.push('monthly_limit = ?'); setParams.push(u.monthly_limit); }
        if (u.category) { sets.push('category = ?'); setParams.push(u.category); }
        if (sets.length === 0) return 0;

        const conditions = ['user_id = ?'];
        const whereParams: unknown[] = [userId];
        if (f.id) { conditions.push('id = ?'); whereParams.push(f.id); }
        else if (f.category) {
            conditions.push('LOWER(category) = LOWER(?)'); whereParams.push(f.category);
            conditions.push('month = ?'); whereParams.push(currentMonth);
            conditions.push('year = ?'); whereParams.push(currentYear);
        }
        return (await run(`UPDATE budgets SET ${sets.join(', ')} WHERE ${conditions.join(' AND ')}`, [...setParams, ...whereParams])).rowsAffected;
    }

    if (action.target === 'networth') {
        const sets: string[] = [];
        const setParams: unknown[] = [];
        if (u.amount !== undefined && u.amount !== null) { sets.push('amount = ?'); setParams.push(u.amount); }
        if (u.note) { sets.push('note = ?'); setParams.push(u.note); }
        if (sets.length === 0) return 0;
        if (f.id) return (await run(`UPDATE net_worth SET ${sets.join(', ')} WHERE id = ? AND user_id = ?`, [...setParams, f.id, userId])).rowsAffected;

        const latest = await queryOne<{ id: number }>('SELECT id FROM net_worth WHERE user_id = ? ORDER BY created_at DESC LIMIT 1', [userId]);
        if (!latest) return 0;
        return (await run(`UPDATE net_worth SET ${sets.join(', ')} WHERE id = ? AND user_id = ?`, [...setParams, latest.id, userId])).rowsAffected;
    }

    if (action.target === 'debts') {
        const sets: string[] = [];
        const setParams: unknown[] = [];
        if (u.name) { sets.push('name = ?'); setParams.push(u.name); }
        if (u.balance !== undefined && u.balance !== null) { sets.push('balance = ?'); setParams.push(u.balance); }
        else if (u.amount !== undefined && u.amount !== null) { sets.push('balance = ?'); setParams.push(u.amount); }
        if (u.interest_rate_apr !== undefined && u.interest_rate_apr !== null) { sets.push('interest_rate_apr = ?'); setParams.push(u.interest_rate_apr); }
        if (u.minimum_payment !== undefined && u.minimum_payment !== null) { sets.push('minimum_payment = ?'); setParams.push(u.minimum_payment); }
        if (u.due_day_of_month !== undefined && u.due_day_of_month !== null) { sets.push('due_day_of_month = ?'); setParams.push(u.due_day_of_month); }
        if (u.debt_type) { sets.push('debt_type = ?'); setParams.push(u.debt_type); }
        if (sets.length === 0) return 0;

        const conditions = ['user_id = ?'];
        const whereParams: unknown[] = [userId];
        if (f.id) { conditions.push('id = ?'); whereParams.push(f.id); }
        else if (f.name) { conditions.push('LOWER(name) LIKE LOWER(?)'); whereParams.push(`%${f.name}%`); }
        else if (f.description) { conditions.push('LOWER(name) LIKE LOWER(?)'); whereParams.push(`%${f.description}%`); }

        return (await run(`UPDATE debts SET ${sets.join(', ')} WHERE ${conditions.join(' AND ')}`, [...setParams, ...whereParams])).rowsAffected;
    }

    if (action.target === 'recurring_transactions' || action.target === 'recurring') {
        const sets: string[] = [];
        const setParams: unknown[] = [];
        if (u.name) { sets.push('name = ?'); setParams.push(u.name); }
        if (u.amount !== undefined && u.amount !== null) { sets.push('amount = ?'); setParams.push(u.amount); }
        if (u.category) { sets.push('category = ?'); setParams.push(u.category); }
        if (u.frequency) { sets.push('frequency = ?'); setParams.push(u.frequency); }
        if (u.type) { sets.push('type = ?'); setParams.push(u.type); }
        if (u.next_date) { sets.push('next_date = ?'); setParams.push(u.next_date); }
        if (sets.length === 0) return 0;

        const conditions = ['user_id = ?'];
        const whereParams: unknown[] = [userId];
        if (f.id) { conditions.push('id = ?'); whereParams.push(f.id); }
        else if (f.name) { conditions.push('LOWER(name) LIKE LOWER(?)'); whereParams.push(`%${f.name}%`); }
        else if (f.description) { conditions.push('LOWER(name) LIKE LOWER(?)'); whereParams.push(`%${f.description}%`); }
        else if (f.category) { conditions.push('LOWER(category) = LOWER(?)'); whereParams.push(f.category); }

        return (await run(`UPDATE recurring_transactions SET ${sets.join(', ')} WHERE ${conditions.join(' AND ')}`, [...setParams, ...whereParams])).rowsAffected;
    }

    if (action.target === 'investment_holdings' || action.target === 'investments') {
        const sets: string[] = [];
        const setParams: unknown[] = [];
        if (u.name) { sets.push('name = ?'); setParams.push(u.name); }
        if (u.quantity !== undefined && u.quantity !== null) { sets.push('quantity = ?'); setParams.push(u.quantity); }
        if (u.avg_cost_basis !== undefined && u.avg_cost_basis !== null) { sets.push('avg_cost_basis = ?'); setParams.push(u.avg_cost_basis); }
        else if (u.amount !== undefined && u.amount !== null) { sets.push('avg_cost_basis = ?'); setParams.push(u.amount); }
        if (u.asset_type) { sets.push('asset_type = ?'); setParams.push(u.asset_type); }
        if (u.note) { sets.push('notes = ?'); setParams.push(u.note); }
        if (sets.length === 0) return 0;

        const conditions = ['user_id = ?'];
        const whereParams: unknown[] = [userId];
        if (f.id) { conditions.push('id = ?'); whereParams.push(f.id); }
        else if (f.ticker) { conditions.push('UPPER(ticker) = UPPER(?)'); whereParams.push(f.ticker); }
        else if (f.name) { conditions.push('LOWER(name) LIKE LOWER(?)'); whereParams.push(`%${f.name}%`); }

        return (await run(`UPDATE investment_holdings SET ${sets.join(', ')} WHERE ${conditions.join(' AND ')}`, [...setParams, ...whereParams])).rowsAffected;
    }

    if (action.target === 'accounts') {
        const sets: string[] = [];
        const setParams: unknown[] = [];
        if (u.name) { sets.push('name = ?'); setParams.push(u.name); }
        if (u.account_type) { sets.push('type = ?'); setParams.push(u.account_type); }
        if (u.current_balance !== undefined && u.current_balance !== null) { sets.push('current_balance = ?'); setParams.push(u.current_balance); }
        else if (u.amount !== undefined && u.amount !== null) { sets.push('current_balance = ?'); setParams.push(u.amount); }
        if (u.opening_balance !== undefined && u.opening_balance !== null) { sets.push('opening_balance = ?'); setParams.push(u.opening_balance); }
        if (sets.length === 0) return 0;

        const conditions = ['user_id = ?'];
        const whereParams: unknown[] = [userId];
        if (f.id) { conditions.push('id = ?'); whereParams.push(f.id); }
        else if (f.name) { conditions.push('LOWER(name) LIKE LOWER(?)'); whereParams.push(`%${f.name}%`); }

        return (await run(`UPDATE accounts SET ${sets.join(', ')} WHERE ${conditions.join(' AND ')}`, [...setParams, ...whereParams])).rowsAffected;
    }

    return 0;
}

async function executeCreate(action: DataAction, userId: number, currentMonth: number, currentYear: number): Promise<number> {
    const u = action.updates || {};

    if (action.target === 'transactions') {
        const type = u.type || 'expense';
        const amount = u.amount;
        const category = u.category || 'Other';
        const description = u.description || '';
        const date = u.date || new Date().toISOString().split('T')[0];

        if (!amount || amount <= 0) return 0;

        const result = await run(
            'INSERT INTO transactions (user_id, type, amount, category, description, date) VALUES (?, ?, ?, ?, ?, ?)',
            [userId, type, amount, category, description, date]
        );

        if (result.rowsAffected > 0 && type === 'expense') {
            await maybeCreateBudgetAlert({
                userId,
                type,
                amount,
                category,
                date,
            });
        }

        return result.rowsAffected;
    }

    if (action.target === 'budgets') {
        const category = u.category;
        const monthlyLimit = u.monthly_limit || u.amount;
        if (!category || !monthlyLimit) return 0;

        const month = u.month || currentMonth;
        const year = u.year || currentYear;

        // Upsert: if budget exists for this category+month+year, update it
        const existing = await queryOne<{ id: number }>(
            'SELECT id FROM budgets WHERE user_id = ? AND LOWER(category) = LOWER(?) AND month = ? AND year = ?',
            [userId, category, month, year]
        );

        if (existing) {
            return (await run(
                'UPDATE budgets SET monthly_limit = ? WHERE id = ? AND user_id = ?',
                [monthlyLimit, existing.id, userId]
            )).rowsAffected;
        }

        return (await run(
            'INSERT INTO budgets (user_id, category, monthly_limit, month, year) VALUES (?, ?, ?, ?, ?)',
            [userId, category, monthlyLimit, month, year]
        )).rowsAffected;
    }

    if (action.target === 'savings_goals') {
        const name = u.description || u.name || 'Untitled Goal';
        const targetAmount = u.amount || u.target_amount;
        if (!targetAmount) return 0;

        return (await run(
            'INSERT INTO savings_goals (user_id, name, target_amount, current_amount, target_date) VALUES (?, ?, ?, 0, ?)',
            [userId, name, targetAmount, u.date || null]
        )).rowsAffected;
    }

    if (action.target === 'debts') {
        const name = u.name || u.description || 'New Debt';
        const debtType = (u.debt_type || 'credit_card').toLowerCase();
        const validTypes = ['credit_card', 'personal_loan', 'student_loan', 'bnpl', 'other'];
        const sanitizedType = validTypes.includes(debtType) ? debtType : 'other';
        const balance = u.balance ?? u.amount ?? 0;
        const initialBalance = u.initial_balance ?? balance;
        const interestRateApr = u.interest_rate_apr ?? 0;
        const minimumPayment = u.minimum_payment ?? 0;
        const dueDayOfMonth = u.due_day_of_month ?? 1;

        return (await run(
            `INSERT INTO debts (user_id, name, debt_type, balance, initial_balance, interest_rate_apr, minimum_payment, due_day_of_month)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
            [userId, name, sanitizedType, balance, initialBalance, interestRateApr, minimumPayment, dueDayOfMonth]
        )).rowsAffected;
    }

    if (action.target === 'recurring_transactions' || action.target === 'recurring') {
        const name = u.name || u.description || 'Recurring Item';
        const type = u.type || 'expense';
        const amount = u.amount ?? 0;
        const category = u.category || 'Other';
        const frequency = u.frequency || 'monthly';
        const nextDate = u.next_date || u.date || new Date().toISOString().split('T')[0];
        const active = 1;

        return (await run(
            `INSERT INTO recurring_transactions (user_id, name, type, amount, category, frequency, next_date, active)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
            [userId, name, type, amount, category, frequency, nextDate, active]
        )).rowsAffected;
    }

    if (action.target === 'investment_holdings' || action.target === 'investments') {
        const ticker = (u.ticker || u.name || 'HOLDING').toUpperCase();
        const name = u.name || u.description || ticker;
        const assetType = u.asset_type || 'stock';
        const quantity = u.quantity ?? 1;
        const avgCostBasis = u.avg_cost_basis ?? u.amount ?? 0;
        const currency = u.currency || 'USD';
        const notes = u.note || '';

        return (await run(
            `INSERT INTO investment_holdings (user_id, asset_type, ticker, name, quantity, avg_cost_basis, currency, notes)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
            [userId, assetType, ticker, name, quantity, avgCostBasis, currency, notes]
        )).rowsAffected;
    }

    if (action.target === 'accounts') {
        const name = u.name || u.description || 'Checking Account';
        const type = u.account_type || 'bank';
        const currency = u.currency || 'BDT';
        const openingBalance = u.opening_balance ?? u.amount ?? 0;
        const currentBalance = u.current_balance ?? openingBalance;

        return (await run(
            `INSERT INTO accounts (user_id, name, type, currency, opening_balance, current_balance)
             VALUES (?, ?, ?, ?, ?, ?)`,
            [userId, name, type, currency, openingBalance, currentBalance]
        )).rowsAffected;
    }

    return 0;
}

export async function storeFinancialData(
    financialData: ParsedFinancialData[],
    userId: number,
    today: string,
    currencySymbol = '$'
): Promise<StoredTransaction[]> {
    const stored: StoredTransaction[] = [];

    for (const entry of financialData) {
        const date = entry.date || today;
        const result = await run(
            'INSERT INTO transactions (user_id, type, amount, category, description, date) VALUES (?, ?, ?, ?, ?, ?)',
            [userId, entry.type, entry.amount, entry.category, entry.description, date]
        );

        const transaction = { id: result.lastInsertRowid, ...entry, date };
        stored.push(transaction);
        await maybeCreateBudgetAlert({
            userId,
            type: entry.type,
            amount: entry.amount,
            category: entry.category,
            date,
            currencySymbol,
        });
    }

    return stored;
}
